name: Generate ASCII Artwork
on:
    - push

jobs:
    ascii_artwork:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: list all files
              run: ls -lart
            
            - name: Execute a script
              run: |
                echo "PWD: $PWD"
                chmod +x ./ascii-script.sh
                ./ascii-script.sh