name: Generate ASCII Artwork
on:
    - push

jobs:
    ascii_artwork:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Execute a script
              run: ascii-script.sh