name: Workflow Filters & Activities
on:
    workflow_dispatch: 
    # schedule:
    #     - cron: "*/1 * * * *"
    push:
        # branches-ignore: 
        #     - feature/*
        #     - test/**
        branches: 
            - main
            - '!feature/*' # ignore branch starting with filter
    
    pull_request: 
        types: 
            - closed
            - opened
        paths-ignore: 
            - README.md
        branches: 
            - main

jobs:
    workflow_filters:
        runs-on: ubuntu-latest
        steps:
            - run: echo "The job is executed with ${{ github.event_name }}"